project = "pluma-csv2json-plugin"
copyright = "2020, Joseph R. Quinn <quinn.josephr@protonmail.com>"
author = "Joseph R. Quinn <quinn.josephr@protonmail.com>"
release = "v0.1.0"
extensions = ["breathe"]
templates_path = ["_templates"]
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]
html_theme = "sphinx_rtd_theme"
html_static_path = ["_static"]
breathe_default_project = "pluma-csv2json-plugin"
